### ISSUE TITLE
Compilation error with USE_RS_HFIQ not defined

### ISSUE THREAD

**Issue by G3ZQC** [K7MDL2/KEITHSDR#8]
Using the Arduino IDE get the following compilation error when "USE_RS_HFIQ" is **not** defined:  

**Controls.cpp: In function 'void VFO_AB()':
Controls.cpp:503: error: 'RS_HFIQ' was not declared in this scope
         if (RS_HFIQ.find_new_band(old_VFOB, &curr_band))  // return the updated band index for the new freq
             ^**
Only discovered this by accident.  I thought that USE_RF_HFIQ had been defined, but that was in your personal definitions.  

Jim G3ZQC

**Comment by K7MDL2** [comment]
I fixed that last night, please pull down the latest.

Sent from my T-Mobile 4G LTE Device
Get Outlook for Android<https://aka.ms/ghei36>
________________________________
From: G3ZQC ***@***.***>
Sent: Monday, May 9, 2022 1:04:43 PM
To: K7MDL2/KEITHSDR ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [K7MDL2/KEITHSDR] Compilation error with USE_RS_HFIQ not defined (Issue #8)


Using the Arduino IDE get the following compilation error when "USE_RS_HFIQ" is not defined:

Controls.cpp: In function 'void VFO_AB()':
Controls.cpp:503: error: 'RS_HFIQ' was not declared in this scope
if (RS_HFIQ.find_new_band(old_VFOB, &curr_band)) // return the updated band index for the new freq
^
Only discovered this by accident. I thought that USE_RF_HFIQ had been defined, but that was in your personal definitions.

Jim G3ZQC

**Comment by G3ZQC** [comment]
Still fails with me:  
Controls.cpp:501
 **#ifndef** USE_RS_HFIQ
        // Compute the band index for the new target band an ensure it is in limits
        if (RS_HFIQ.find_new_band(old_VFOB, &curr_band))  // return the updated band index for the new freq
    #else
        if (find_new_band(old_VFOB, &curr_band))
    #endif

Loos like #ifndef should be #ifdef?  

Are you happy for these things to be raised on Github, or should I use the forum?  

rgds

**Comment by K7MDL2** [comment]
You are correct, i had the ifndef for testing, must have missed setting it back to ifdef.

I will fix it tonight.

You can raise issues here, i read everything. Thanks for reporting that.

Sent from my T-Mobile 4G LTE Device
Get Outlook for Android<https://aka.ms/ghei36>
________________________________
